"""obele - a lightweight, async-ready ORM and key-value store for SQLite.

Usage:

    from obele import Database, Model, TextField, IntegerField

    Database.configure("my_app.sqlite3")

    class User(Model):
        table_name = "users"
        name = TextField()
        age  = IntegerField(nullable=True)

    User.create_table()
    alice = User.create(name="Alice", age=30)
    users = User.filter(age__gte=18).order_by("name").all()

    # The same API is async-ready:
    users = await User.filter(age__gte=18).order_by("name").aall()
"""

from ._identity import PACKAGE_NAME
from .orm import (
	Database,
	DatabaseScope,
	ExecResult,
	Transaction,
	Field,
	IntegerField,
	TextField,
	RealField,
	BlobField,
	DecimalField,
	UUIDField,
	BooleanField,
	DateTimeField,
	DateField,
	TimestampField,
	JSONField,
	ForeignKeyField,
	EnumField,
	TimeField,
	SlugField,
	EmailField,
	PickleField,
	IPAddressField,
	Model,
	ReverseRelationManager,
	ReverseRelationDescriptor,
	create_all,
	acreate_all,
	drop_all,
	adrop_all,
	registered_models,
	QuerySet,
	Q,
	F,
	Value,
	RawSQL,
	Func,
	CombinedExpression,
	Count,
	Sum,
	Avg,
	Min,
	Max,
	Subquery,
	TimestampMixin,
	SoftDeleteMixin,
	Page,
	CursorPage,
	SearchIndex,
	Signal,
	pre_save,
	post_save,
	pre_delete,
	post_delete,
	pre_create,
	post_create,
	receiver,
	ORMError,
	FieldValidationError,
	RecordNotFoundError,
	MultipleResultsError,
	DatabaseError,
	IntegrityError,
	MigrationError,
	ConfigurationError,
)
from .kv import KVStore, KV

__title__ = PACKAGE_NAME

__all__ = [
	"Database",
	"DatabaseScope",
	"ExecResult",
	"Transaction",
	"Model",
	"ReverseRelationManager",
	"ReverseRelationDescriptor",
	"create_all",
	"acreate_all",
	"drop_all",
	"adrop_all",
	"registered_models",
	"QuerySet",
	"Q",
	"F",
	"Value",
	"RawSQL",
	"Func",
	"CombinedExpression",
	"Count",
	"Sum",
	"Avg",
	"Min",
	"Max",
	"Subquery",
	"Field",
	"IntegerField",
	"TextField",
	"RealField",
	"BlobField",
	"DecimalField",
	"UUIDField",
	"BooleanField",
	"DateTimeField",
	"DateField",
	"TimestampField",
	"JSONField",
	"ForeignKeyField",
	"EnumField",
	"TimeField",
	"SlugField",
	"EmailField",
	"PickleField",
	"IPAddressField",
	"TimestampMixin",
	"SoftDeleteMixin",
	"Page",
	"CursorPage",
	"SearchIndex",
	"Signal",
	"pre_save",
	"post_save",
	"pre_delete",
	"post_delete",
	"pre_create",
	"post_create",
	"receiver",
	"ORMError",
	"FieldValidationError",
	"RecordNotFoundError",
	"MultipleResultsError",
	"DatabaseError",
	"IntegrityError",
	"MigrationError",
	"ConfigurationError",
	"KVStore",
	"KV",
]
